#!/bin/bash
#
#BSUB -q 52-large
#BSUB -W 24:00
#BSUB -J iter_elec_eps
#BSUB -o cp2k.%J.stdout
#BSUB -e cp2k.%J.stderr
#BSUB -n 28
#BSUB -R "span[ptile=28]"

# add modulefiles
module load miniconda/3
source activate gnn
module load mkl/latest mpi/latest gcc/9.3.0
module load cp2k/9.1

python run.py
